# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyRealTrip' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CalendarDateRangePickerViewController', '~> 0.1'
  pod 'KWStepper', '~> 2.4'
  pod 'MBRadioCheckboxButton'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.1'

  # Pods for MyRealTrip

end
